### ISSUE TITLE
Incompatible with Postgres? InvalidCastException

### ISSUE THREAD

**Issue by alecgorge** [pieceofsummer/Hangfire.Console#17]
Whenever a job should complete, it is failing because of an error here:

```
System.InvalidCastException

Unable to cast object of type 'Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.

System.InvalidCastException: Unable to cast object of type 'Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.
   at Hangfire.Console.Storage.ConsoleStorage.Expire(ConsoleId consoleId, TimeSpan expireIn)
   at Hangfire.Console.Server.ConsoleServerFilter.OnPerformed(PerformedContext context)
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
```

I am investigating this now but recording here for others to find.

**Comment by alecgorge** [comment]
Update: I gave up and switched to the Redis backend. The Postgres backend doesn't seem to support ExpireSet, etc because it only inherits from IWriteOnlyTransaction instead of JobStorageTransaction

**Comment by pieceofsummer** [comment]
Seems so :(

I could probably make it not fail because of expiration, but it might be not the only place where it is not compatible.

**Comment by alecgorge** [comment]
Is this something that can be worked around in Hangfire.Console? Or would my effort be better served to add ExpireSet to the Postgres backend?

**Comment by pieceofsummer** [comment]
I think there's some more missing methods in Postgres provider, like `JobStorageConnection.GetValueFromHash`, alas.

**Comment by ericjacobsson** [comment]
I'm getting an identical error with MongoDb storage as well after a job has finished:

```
System.InvalidCastException

Unable to cast object of type 'Hangfire.Mongo.MongoWriteOnlyTransaction' to type  'Hangfire.Storage.JobStorageTransaction'.

System.InvalidCastException: Unable to cast object of type 'Hangfire.Mongo.MongoWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.
   at Hangfire.Console.Storage.ConsoleStorage.Expire(ConsoleId consoleId, TimeSpan expireIn)
   at Hangfire.Console.Server.ConsoleServerFilter.OnPerformed(PerformedContext context)
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
```

**Comment by pieceofsummer** [comment]
@ericjacobbson which MongoDb provider/version do you use? There's at least several different forks out there.

**Comment by ericjacobsson** [comment]
I thought (or rather my NuGet manager was sure) I was using the latest version of https://www.nuget.org/packages/HangFire.Mongo (when running into the bug I updated all the Hangfire components). After upgrading to 0.3.2 everything works just fine. Thanks for the pointer!

**Comment by totalprogrammi** [comment]
Same problem with Postgresql. If I disable Console, everything works fine!

**Comment by pieceofsummer** [comment]
@totalprogrammi cannot be fixed on my side, but you can persuade postgre storage author to implement full api.

**Comment by vytautask** [comment]
@pieceofsummer @totalprogrammi, @alecgorge could you please check if Console is working with current version of Hangfire.Postgresql (v1.4.7)? Thanks.

**Comment by totalprogrammi** [comment]
Now the exception is changed:

warn: Hangfire.Server.Worker[0]
      Error occurred during execution of 'Worker #2750cd9d' process. Execution will be retried (attempt 3 of 2147483647) in 00:00:09 seconds.
System.NotSupportedException: Specified method is not supported.
   at Hangfire.Storage.JobStorageTransaction.PersistSet(String key)
   at Hangfire.Console.Storage.ConsoleExpirationTransaction.Persist(ConsoleId consoleId)
   at Hangfire.Console.States.ConsoleApplyStateFilter.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
   at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context, BackgroundJob backgroundJob, IState toState, String oldStateName)
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

Latest versions applied:

Hangfire: 1.6.11
Hangfire.Core: 1.6.11
Hangfire.Console: 1.3.1
Hangfire.PostgreSql: 1.4.7

**Comment by pieceofsummer** [comment]
@vytautask after a quick look, there are still several unimplemented methods:
- JobStorageTransaction.ExpireSet
- JobStorageTransaction.ExpireHash
- JobStorageTransaction.PersistSet
- JobStorageTransaction.PersistHash

**Comment by vytautask** [comment]
@pieceofsummer thanks. Will look into that.

**Comment by vytautask** [comment]
@pieceofsummer released update. Please check if everything is OK now.

**Comment by pieceofsummer** [comment]
@totalprogrammi can you please check this? I don't have any Postgre server at hand.

**Comment by kyr0s** [comment]
Exception after server restart:
```
Npgsql.PostgresException

40001: не удалось сериализовать доступ из-за зависимостей чтения/записи между транзакциями

Npgsql.PostgresException (0x80004005): 40001: не удалось сериализовать доступ из-за зависимостей чтения/записи между транзакциями
   at Npgsql.NpgsqlConnector.<DoReadMessage>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadExpecting>d__154`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ExecuteInternalCommand>d__209.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlTransaction.<Commit>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlTransaction.Commit()
   at Hangfire.PostgreSql.PostgreSqlConnection.SetRangeInHash(String key, IEnumerable`1 keyValuePairs)
   at Hangfire.Console.Storage.ConsoleStorage.InitConsole(ConsoleId consoleId)
   at Hangfire.Console.Server.ConsoleServerFilter.OnPerforming(PerformingContext filterContext)
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)
```

**Comment by totalprogrammi** [comment]
With last update (Hangfire.PostgreSql 1.4.7.1 and related) everything seems to work perfectly. Thank you for your help!

**Comment by pieceofsummer** [comment]
I'm closing the issue then.

**Comment by senzacionale** [comment]
I got same message now with .net core and postgres. 

Did anyone test this with core version?

**Comment by senzacionale** [comment]
Version I am using 1.4.8.2
