### ISSUE TITLE
DisableConcurrentExecution causes PerformContext.Writeline to through an exception

### ISSUE THREAD

**Issue by rholand3** [pieceofsummer/Hangfire.Console#45]
I added the DisableConcurrentExecution attribute to a job where I'm doing logging, some of it async. Before adding the attribute logging was working fine. As soon as I added the attribute I started getting an exception on `PerformContext.WriteLine`  there Exception message was
```
An exception of type 'System.InvalidOperationException' occurred in System.Data.dll but was not handled in user code
Additional information: Connection currently has transaction enlisted.  Finish current transaction and retry. occurred
```

And the stack trace was:

```
  at System.Data.SqlClient.SqlConnection.EnlistTransaction(Transaction transaction)
   at Hangfire.SqlServer.SqlServerStorage.<>c__DisplayClass27_0`1.<UseTransaction>b__0(DbConnection connection)
   at Hangfire.SqlServer.SqlServerStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction[T](DbConnection dedicatedConnection, Func`3 func, Nullable`1 isolationLevel)
   at Hangfire.SqlServer.SqlServerStorage.UseTransaction(DbConnection dedicatedConnection, Action`2 action)
   at Hangfire.SqlServer.SqlServerWriteOnlyTransaction.Commit()
   at Hangfire.Console.Storage.ConsoleStorage.AddLine(ConsoleId consoleId, ConsoleLine line)
   at Hangfire.Console.Server.ConsoleContext.AddLine(ConsoleLine line)
   at Hangfire.Console.Server.ConsoleContext.WriteLine(String value, ConsoleTextColor color)
   at Hangfire.Console.ConsoleExtensions.WriteLine(PerformContext context, String value)
```

**Comment by pieceofsummer** [comment]
Try using [MutexAttribute](https://gist.github.com/odinserj/4a3bf40606c4da9183588a5a325dfb99) instead. It works fine with Console and doesn't block other workers waiting for the same resource.

Of course, I could open a dedicated connection solely for Console writes, but doing so only because of one attribute feels like a waste.

**Comment by pieceofsummer** [comment]
After the second thought, I cannot even do that. `Storage` is not exposed to state filters, so there's no way to open another connection at all.

So it's probably impossible to make it work with `DisableConcurrentExecution` attribute for some storages.

**Comment by pieceofsummer** [comment]
@odinserj it would probably be reasonable to add `Storage` property to `PerformContext` (to make it consistent with `CreateContext`).

**Comment by odinserj** [comment]
@pieceofsummer, I've added the corresponding feature request, please see https://github.com/HangfireIO/Hangfire/issues/1044.

**Comment by natiki** [comment]
When using Mutex (https://github.com/pieceofsummer/Hangfire.Console/issues/45#issuecomment-336412697) what is the ResourceName parameter supposed to be?

**Comment by pieceofsummer** [comment]
@natiki it can be any identifier you want. You may consider it as a lock variable in c#: `lock (resource) { ... }` block. 

Two jobs won't be executed concurrently if they have the same resource name. It can be just class name + method name or even include method arguments (it supports `string.Format` syntax).
