### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'Hangfire.Couchbase.CouchbaseWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.

### ISSUE THREAD

**Issue by bbollard** [pieceofsummer/Hangfire.Console#68]
Hello,
I'm  using the Hangfire.Couchbase storage provider and when the Hangfire.Console (1.4.0) is enabled I am getting the following exception:

System.InvalidCastException: Unable to cast object of type 'Hangfire.Couchbase.CouchbaseWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.
at Hangfire.Console.States.ConsoleApplyStateFilter.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken cancellationToken)
at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

Which seems to point to : https://github.com/pieceofsummer/Hangfire.Console/blob/39d728ff7934206b1ca7d4dbab4c90c591c97c62/src/Hangfire.Console/States/ConsoleApplyStateFilter.cs#L36

Thank you,
Brian

**Comment by pieceofsummer** [comment]
This happens when the job storage doesn’t implement a full set of methods. Having a full JobStorageConnection and JobStorageTransaction implemented is a prerequisite for Hangfire.Console to work.

You should ask Hangfire.Couchbase authors to implement those (or fork it and implement those yourself).

**Comment by bbollard** [comment]
The Hangfire.Couchbase author agrees with the assessment. Thanks for your help with this!
